name: Deploy to Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            template
            solutions

      - name: Install nbconvert
        run: pip install nbconvert

      - name: Install IPython
        run: pip install ipython

      - name: Copy template
        run: mkdir -p /home/runner/.local/share/jupyter/nbconvert/templates/aoc/static/ && cp -r /home/runner/work/advent-of-code/advent-of-code/template/aoc/ /home/runner/.local/share/jupyter/nbconvert/templates/

      - name: Convert .ipynb to .html
        run: find . -name '*.ipynb' -type f -execdir jupyter nbconvert --template aoc --to html {} \; -execdir rm {} \;

      - name: Replace links
        run: find . -name '*.html' -type f -execdir sed -i 's/.ipynb">/.html">/g' {} \; && find . -name '*.html' -type f -execdir sed -i 's/.ipynb#----Part-Two----">/.html#----Part-Two----">/g' {} \; && find . -name '*.html' -type f -execdir sed -i 's/\*\*(.*?)\*\*/<strong>\1<\/strong>/g' {} \;

      - name: Push to gh-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          FOLDER: solutions
          BRANCH: gh-pages
          TARGET_DIR: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: ({sha}) {msg}"
          SQUASH_HISTORY: true
          CLEAR_GLOBS_FILE: '.targets'
