name: Deploy to Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install nbconvert
        run: pip install nbconvert

      - name: Copy template
        run: cp -r /home/runner/work/advent-of-code/advent-of-code/template/ /usr/local/share/jupyter/

      - name: Convert .ipynb to .html
        run: find . -name '*.ipynb' -type f -execdir jupyter nbconvert --TemplateExporter.extra_template_basedirs=template --template aoc --to html {} \; -execdir rm {} \;

      - name: Push to gh-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          FOLDER: solutions
          BRANCH: gh-pages
          TARGET_DIR: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: ({sha}) {msg}"
          SQUASH_HISTORY: true
